# Dependencies
markdown:         kramdown
highlighter:      rouge
include:          ['_pages']

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Introduction to Latin
tagline:          'LATN 102'
course_number:    'LATN 102'
semester:         'Spring 2020'
location:         'College of the Holy Cross'
url:              https://libatique.info/LATN102-S20
baseurl:          /

author:
  name:           'Daniel Libatique'
  url:            https://libatique.info

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dlibatique/LATN102-S20
